"""empty message

Revision ID: 3c8e8d8aa090
Revises: d233e72cc645
Create Date: 2023-09-17 17:16:37.743347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8e8d8aa090'
down_revision = 'd233e72cc645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
